# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171108_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='abbrev',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
