# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_university_abbrev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='courses',
            new_name='course',
        ),
    ]
