# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171108_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailabletimeslot',
            name='tutor',
        ),
        migrations.AddField(
            model_name='session',
            name='isBlackout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
        migrations.DeleteModel(
            name='UnavailableTimeslot',
        ),
    ]
