# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171109_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='isBlackout',
            new_name='isBlackedout',
        ),
    ]
