# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTutorTempUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=32, unique=True)),
                ('expires', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tutor')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='isAnonymous',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
