# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171111_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewTutorTempUrl',
            new_name='ReviewTempUrl',
        ),
    ]
