# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171112_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='isCouponUsed',
            field=models.BooleanField(default=False),
        ),
    ]
