# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 07:03
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20171112_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='checked_date',
        ),
        migrations.AddField(
            model_name='notification',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='no title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
