# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171112_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='to_or_from_bank',
            new_name='isBankRelated',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='to_or_from_system',
            new_name='isSystemRelated',
        ),
        migrations.AddField(
            model_name='transaction',
            name='isTutorFeeRelated',
            field=models.BooleanField(default=False),
        ),
    ]
