# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20171123_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='involved_profile',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
