# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20171123_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='isHideProfile',
            field=models.BooleanField(default=False),
        ),
    ]
